#!/usr/bin/env bash

# Ensure dependencies are installed
if ! [ -x "$(command -v docker)" ] || ! [ -x "$(command -v docker-compose)" ]; then
  echo "You must install docker and docker-compose to use this script."
fi

# Provide the clean command
if [ "$1" == "clean" ]; then
  echo "WARNING: This command is destructive. It removes all containers, images and volumes installed on your local machine."
  read -r -p "Are you SURE you want to continue? [y/N]" clean_confirmation
  if [[ $clean_confirmation =~ ^(y|Y)$ ]]; then

    echo "  >>> Killing all docker containers <<<" && echo "" && docker ps -qa | xargs docker kill && echo ""
    echo "  >>> Removing all stopped containers <<<" && echo "" && docker ps -qa | xargs docker rm -v && echo ""
    echo "  >>> Removing all images <<<" && echo "" && docker images -qa | xargs docker rmi && echo ""
    echo "  >>> Removing all volumes <<<" && echo "" && docker volume ls -qf dangling=true | xargs docker volume rm && echo ""

  else
    echo "Clean aborted."
  fi
  exit
fi

# Provide the clean command
if [ "$1" == "lint-fix" ]; then
  if ! [ -x "$(command -v yapf)" ]; then
    echo "You must install yapf to auto-fix Python linting errors. python3 -m pip install yapf."
  fi
  if ! [ -x "$(command -v npm)" ]; then
    echo "You must install node & npm to install front-end dependencies and auto-fix Javascript linting errors."
  fi

  echo " >> Automatically fixing linting errors <<"
  echo ""
  yapf -ir --style google .
  cd ./src/web_client && npm install && npm run lint-fix && cd ../..
  echo ""
fi




# Choose an environment, default is dev
if [ -z "$COMPOSE_FILE" ]; then
    COMPOSE_FILE='dev'
fi

# Passes script arguments to docker-compose
COMPOSE="docker-compose -f docker-compose.base.yml -f docker-compose.$COMPOSE_FILE.yml $@"
bash -c "$COMPOSE"

