version: '3'

services:
  ml_service:
    ports:
      - 3001:3001
    command: python -m flask run --host 0.0.0.0 -p 3001
  nlp_service:
    ports:
      - 3002:3002
    command: python -m flask run --host 0.0.0.0 -p 3002
    environment:
      POSTGRES_PASSWORD: DEV_PASS_NOT_SECRET
  backend_service:
    ports:
      - 3003:3003
    command: python -m flask run --host 0.0.0.0 -p 3003
    environment:
      POSTGRES_PASSWORD: DEV_PASS_NOT_SECRET
  postgresql_db:
    environment:
      POSTGRES_PASSWORD: DEV_PASS_NOT_SECRET
