version: '3'

services:
  ml_service:
    ports:
      - 3001:3001
  nlp_service:
    ports:
      - 3002:3002
  backend_service:
    ports:
      - 3003:3003
  web_client:
    command: npm start
    ports:
      - 3039:3039
  postgresql_db:
    environment:
      - POSTGRES_PASSWORD
