version: '3'

services:
  ml_service:
    ports:
      - 3001:3001
    command: gunicorn -w 3 --log-level DEBUG -b 0.0.0.0:3001 app:app
  nlp_service:
    ports:
      - 3002:3002
    command: python -m flask run --host 0.0.0.0 -p 3002
    environment:
      POSTGRES_PASSWORD: DEV_PASS_NOT_SECRET
  backend_service:
    ports:
      - 3003:3003
    command: gunicorn -w 3 --log-level DEBUG -b 0.0.0.0:3003 app:app
    environment:
      POSTGRES_PASSWORD: DEV_PASS_NOT_SECRET
  ocr_service:
    ports:
      - 3004:3004
    command: python -m flask run --host 0.0.0.0 -p 3004
    environment:
      POSTGRES_PASSWORD: DEV_PASS_NOT_SECRET
  web_client:
    command: npm start
    ports:
      - 3039:3039
  postgresql_db:
    environment:
      POSTGRES_PASSWORD: DEV_PASS_NOT_SECRET
