version: '3'

services:
  ml_service:
    build:
      context: .
      dockerfile: ./src/ml_service/Dockerfile
      args:
      - CJL_USER
      - CJL_PASS
    image: procezeus/ml_service
    restart: always
    networks:
      - procezeus_net
  nlp_service:
    build:
      context: .
      dockerfile: ./src/nlp_service/Dockerfile
      args:
      - CJL_USER
      - CJL_PASS
    image: procezeus/nlp_service
    restart: always
    networks:
      - procezeus_net
  backend_service:
    build:
      context: .
      dockerfile: ./src/backend_service/Dockerfile
    image: procezeus/backend_service
    restart: always
    depends_on:
      - postgresql_db
      - nlp_service
    networks:
      - procezeus_net
  web_client:
    build:
      context: .
      dockerfile: ./src/web_client/Dockerfile
    restart: always
    image: procezeus/web_client
    depends_on:
      - backend_service
    networks:
      - procezeus_net
  postgresql_db:
    image: postgres
    restart: always
    volumes:
      - procezeus_db:/var/lib/postgresql/data
    networks:
      - procezeus_net
volumes:
  procezeus_db:
    driver: "local"
networks:
  procezeus_net:
    driver: "bridge"
