version: '3'

services:
  ml_service:
    build: ./src/ml_service
    image: procezeus/ml_service
  nlp_service:
    build: ./src/nlp_service
    image: procezeus/nlp_service
  backend_service:
    build: ./src/backend_service
    image: procezeus/backend_service
  web_client:
    build: ./src/web_client
    image: procezeus/web_client
