export default {
  difficult_word_definitions: {
    abandoned: 'having been deserted or left',
    abandonment: 'the action or fact of abandoning or being abandoned',
    abide: 'accept or act in accordance with (a rule, decision, or recommendation)',
    access: 'the means or opportunity to approach or enter a place',
    acquire: 'buy or obtain (an asset or object) for oneself',
    aid: 'help, typically of a practical nature',
    allowable: 'allowed, especially within a set of regulations; permissible',
    area: 'a region or part of a town, a country, or the world',
    assign: 'allocate (a job or duty)',
    assignment: 'a task or piece of work allocated to someone as part of a job or course of study',
    authorization: 'the action of authorizing',
    available: "able to be used or obtained; at someone's disposal",
    aware: 'having knowledge or perception of a situation or fact',
    beneficial: 'resulting in good; favourable or advantageous',
    bylaw: 'a regulation made by a local authority or corporation.',
    cancellation: 'the action of cancelling something',
    cease: 'come or bring to an end',
    chronological: '(of a record of events) following the order in which they occurred',
    civil: 'relating to ordinary citizens and their concerns, as distinct from military or ecclesiastical matters',
    clause: 'a unit of grammatical organization next below the sentence in rank and in traditional grammar said to consist of a subject and predicate.',
    climatic: 'relating to climate',
    code: 'a system of words, letters, figures, or symbols used to represent others, especially for the purposes of secrecy',
    commission: 'an instruction, command, or role given to a person or group',
    commissioner: 'a person appointed to a role on or by a commission.',
    communication: 'the imparting or exchanging of information by speaking, writing, or using some other medium',
    compensation: 'something, typically money, awarded to someone in recognition of loss, suffering, or injury',
    consent: 'permission for something to happen or agreement to do something',
    consult: 'seek information or advice from (someone, especially an expert or professional)',
    consultation: 'the action or process of formally consulting or discussing',
    contact: 'the state of physical touching',
    continually: 'repeated frequently in the same way; regularly',
    courthouse: 'a building in which a judicial court is held.',
    credit: 'the ability of a customer to obtain goods or services before payment, based on the trust that payment will be made in the future',
    deem: 'regard or consider in a specified way',
    device: 'a thing made or adapted for a particular purpose, especially a piece of mechanical or electronic equipment',
    discontent: "dissatisfaction with one's circumstances; lack of contentment",
    displayed: '(of information) shown on a computer screen or other device',
    disruptive: 'causing or tending to cause disruption',
    document: 'a piece of written, printed, or electronic matter that provides information or evidence or that serves as an official record.',
    driver: 'a person who drives a vehicle',
    dwelling: 'a house, flat, or other place of residence',
    eligible: 'having the right to do or obtain something; satisfying the appropriate conditions',
    energy: 'the strength and vitality required for sustained physical or mental activity',
    establish: 'set up on a firm or permanent basis',
    estimate: 'roughly calculate or judge the value, number, quantity, or extent of',
    evidence: 'the available body of facts or information indicating whether a belief or proposition is true or valid',
    excessive: 'more than is necessary, normal, or desirable; immoderate',
    external: 'belonging to or forming the outer surface or structure of something',
    fee: 'a payment made to a professional person or to a professional or public body in exchange for advice or services',
    file: 'a folder or box for holding loose papers together and in order for easy reference',
    filing: 'a small particle rubbed off by a file when smoothing or shaping something',
    finally: 'after a long time, typically when there has been difficulty or delay',
    financial: 'relating to finance',
    financially: 'in a way that relates to finance',
    granted: 'admittedly; it is true (used to introduce a factor which is opposed to the main line of argument but is not regarded as so strong as to invalidate it)',
    habitation: 'the fact of living in a particular place',
    harassment: 'aggressive pressure or intimidation',
    identification: 'the action or process of identifying someone or something or the fact of being identified',
    illegal: 'contrary to or forbidden by law, especially criminal law',
    income: 'money received, especially on a regular basis, for work or through investments',
    indemnity: 'security or protection against a loss or other financial burden',
    indisposed: 'slightly unwell',
    infrastructure: 'the basic physical and organizational structures and facilities (e.g. buildings, roads, power supplies) needed for the operation of a society or enterprise',
    inhabitable: 'suitable to live in; habitable',
    injury: 'an instance of being injured',
    inspector: 'an official employed to ensure that official regulations are obeyed, especially in public services',
    invalid: 'a person made weak or disabled by illness or injury',
    job: 'a paid position of regular employment',
    jurisdiction: 'the official power to make legal decisions and judgements',
    justify: 'show or prove to be right or reasonable',
    landlord: 'a man (in legal use also a woman) who rents out land, a building, or accommodation.',
    legal: 'relating to the law',
    license: 'grant a licence to',
    lodge: 'a small house at the gates of a park or in the grounds of a large house, occupied by a gatekeeper, gardener, or other employee.',
    maintenance: 'the process of preserving a condition or situation or the state of being preserved',
    mandatary: 'a person or state receiving a mandate.',
    minimize: 'reduce (something, especially something undesirable, to the smallest possible amount or degree',
    municipal: 'relating to a town or district or its governing body',
    mutually: 'with mutual action; in a mutual relationship',
    negligence: 'failure to take proper care over something',
    negligent: 'failing to take proper care over something',
    notify: 'inform (someone, of something, typically in a formal or official manner',
    obtain: 'get, acquire, or secure (something,',
    pest: 'a destructive insect or other animal that attacks crops, food, livestock, etc.',
    plead: 'make an emotional appeal',
    postponement: 'the action of postponing something; deferral',
    prejudice: 'preconceived opinion that is not based on reason or actual experience',
    previous: 'existing or occurring before in time or order',
    prior: 'existing or coming before in time, order, or importance',
    professional: 'relating to or belonging to a profession',
    receptive: 'willing to consider or accept new suggestions and ideas',
    recipient: 'a person or thing that receives or is awarded something',
    recourse: 'a source of help in a difficult situation',
    recover: 'return to a normal state of health, mind, or strength',
    refrain: 'stop oneself from doing something',
    refund: 'pay back (money,, typically to a customer who is not satisfied with goods or services bought',
    regie: 'In France and certain other European countries: a government department that controls an industry or service; specifically one with complete control of the importation, manufacture, and taxation of tobacco, salt, and other resources (now historical,. Also: a government monopoly used as a means of taxation; especially the tobacco monopoly in the former Turkish Empire (now historical,.',
    registered: 'entered or recorded on an official list or directory',
    relocation: "the action of moving to a new place and establishing one's home or business there",
    rendered: '(of fat, melted in order to separate out the impurities',
    rental: 'an amount paid or received as rent',
    reputable: 'having a good reputation',
    require: 'need for a particular purpose',
    resiliate: 'To annul, cancel (a bargain, contract, etc.,. Chiefly Canadian Law in later use.',
    respond: 'say something in reply',
    response: 'a verbal or written answer',
    retake: 'take (something, again',
    security: 'the state of being free from danger or threat',
    sin: 'an immoral act considered to be a transgression against divine law',
    solidarity: 'unity or agreement of feeling or action, especially among individuals with a common interest; mutual support within a group',
    source: 'a place, person, or thing from which something originates or can be obtained',
    specific: 'clearly defined or identified',
    specifically: 'in a way that is exact and clear; precisely',
    spousal: 'relating to marriage or to a husband or wife',
    spouse: 'a husband or wife, considered in relation to their partner.',
    sublet: 'lease (a property, to a subtenant',
    submit: 'accept or yield to a superior force or to the authority or will of another person',
    subtenant: 'a person who leases property from a tenant.',
    technically: 'according to the facts or exact meaning of something; strictly',
    temporary: 'lasting for only a limited period of time; not permanent',
    testimony: 'a formal written or spoken statement, especially one given in a court of law',
    text: 'a book or other written or printed work, regarded in terms of its content rather than its physical form',
    transfer: 'move from one place to another',
    unfit: '(of a thing, not of the necessary quality or standard to meet a particular purpose',
    uninhabitable: '(of a place, unsuitable for living in'
  }
}
